language: c++
dist: trusty
sudo: required
group: edge
addons:
    apt:
      sources:
      - ubuntu-toolchain-r-test
      packages:
      - gcc-4.9
      - g++-4.9
git:
    submodules: true
before_install:
  - git fetch --recurse-submodules
  - travis_retry wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_8.0.44-1_amd64.deb
  - travis_retry sudo dpkg -i cuda-repo-ubuntu1404_8.0.44-1_amd64.deb
  - travis_retry sudo apt-get update -qq
  - travis_retry sudo apt-get install -y cuda-drivers cuda-core-8.0 cuda-cudart-dev-8-0 cuda-cufft-dev-8-0
  - travis_retry sudo apt-get clean
  - export CUDA_HOME=/usr/local/cuda-8.0
  - export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
  - export PATH=${CUDA_HOME}/bin:${PATH}
  - sudo rm /usr/bin/g++ /usr/bin/gcc
  - sudo ln -s /usr/bin/g++-4.9 /usr/bin/g++
  - sudo ln -s /usr/bin/gcc-4.9 /usr/bin/gcc
  # install ndk
  - travis_retry wget http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin
  - chmod u+x android-ndk-r10e-linux-x86_64.bin
  - ./android-ndk-r10e-linux-x86_64.bin > /dev/null
  - export ANDROID_NDK=`pwd`/android-ndk-r10e
  - export ANDROID_NDK_HOME="$ANDROID_NDK_HOME"
  - export PATH=$PATH:${ANDROID_NDK_HOME}
script:
  - mkdir build && cd build && cmake .. -DWITH_CUDA=ON -DWITH_BENCHMARK=ON && make
  - cd ..
  - chmod +x ./script/build_android.sh
  - ./script/build_android.sh
